In [ ]:
print("hello")

hello


In [ ]:
pi = 3.1459265
r = 10

In [ ]:
print("원주율:", pi)
print("반지름:", r)
print("넓이:", pi*r**2)
print()
print("yes")

원주율: 3.1459265
반지름: 10
넓이: 314.59265

yes


In [ ]:
raw_input = input("inch 단위의 숫자를 입력해주세요: ")
inch = int(raw_input)
cm = inch * 2.54
print("변환한 값:", cm)

inch 단위의 숫자를 입력해주세요: 21
변환한 값: 53.34


In [ ]:
a = 7

if a < 12:
    print("Good morning")
elif a < 17:
    print("Good afternoon")
elif a < 21:
    print("Good evening")
else:
    print("Good night")

Good morning


In [ ]:
import datetime

now = datetime.datetime.now()
month = now.month

if 3 <= month <= 5:
    print("현재는 봄")
elif 6 <= month <= 8:
    print("현재는 여름")
elif 9 <= month <= 11:
    print("현재는 가을")
else:
    print("현재는 겨울")

현재는 여름


In [ ]:
score = float(input("당신의 학점은?"))

if score == 4.5:
    print("당신은 짱")
elif 4.0 <= score < 4.5:
    print("와아~")
elif 3.5 <= score < 4.0:
    print("그래도 와~")
elif 3.0 <= score < 3.5:
    print("좀 더 파이팅~~")
else:
    print("분발해보자고~~~")

당신의 학점은?4.1
와아~


In [ ]:
hour = now.hour
if hour >= 12:
    print("오후")
else:
    print("오전")

오후


In [ ]:
import numpy as np

print(np.zeros(10))
print(np.ones(10))

print(np.random.rand(10))   # 난수 생성

print(np.arange(1, 10, 2))  # 시작하는 수, 끝나는 수, 간격
print(np.linspace(1, 10, 2)) # 시작하는 수, 끝나는 수, 원소 수

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
[0.15927281 0.64534294 0.56481456 0.60785731 0.12694561 0.67180055
 0.21158326 0.16519229 0.5347136  0.62002243]
[1 3 5 7 9]
[ 1. 10.]


In [ ]:
a = np.array([0, 1, 2, 3, 4, 5, 6, 7])
b = a.reshape(2, 4)
print(b)

[[0 1 2 3]
 [4 5 6 7]]


In [ ]:
c = b.reshape(-1)  # 1차원 배열로 변환
print(c)

[0 1 2 3 4 5 6 7]


In [ ]:
e = a.reshape(2, -1) # -1로 주면 배열 자동으로 계산
print(e)

[[0 1 2 3]
 [4 5 6 7]]
